test_project:
  outputs:
    dev:
      type: postgres
      threads: 4
      host: postgres
      port: 5432
      user: postgres
      pass: postgres
      dbname: dbt
      schema: dbt
  target: dev
